name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Coverage
      run: lein cloverage --coveralls
    - name: Publish
      env:
        CLOJARS_USER: ${{ secrets.CLOJAR_USERNAME}}
        CLOJARS_PASS: ${{ secrets.CLOJAR_PASS }}
      run: lein deploy clojars
